version: '3'

services:
  web:
    image: jwilder/nginx-proxy:alpine
    container_name: ${APP_NAME}_web
    hostname: ${APP_NAME}_web
    environment:
      PROXY_HOST: ${DOCKER_BRIDGE}
      PROXY_PORT: ${PORT}
      ACCESS_LOG: /var/www/storage/logs/access.log
      ERROR_LOG: /var/www/storage/logs/errors.log
    volumes:
      - ./:/var/www:rw,cached
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - ${DOCKER_BRIDGE}:80:80
    depends_on:
      - node
    restart: always

  db:
    image: mysql:5.7.28
    container_name: ${APP_NAME}_db
    hostname: ${APP_NAME}_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DOCKER_BRIDGE}:${DB_PORT}:${DB_PORT}
    volumes:
      - ./storage/mysql:/var/lib/mysql

  db_testing:
    image: mysql:5.7.28
    container_name: ${APP_NAME}_db_testing
    hostname: ${APP_NAME}_db_testing
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DOCKER_BRIDGE}:3307:${DB_PORT}
    tmpfs:
      - /var/lib/mysql

  cache:
    image: nbtri/alpine-redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    container_name: ${APP_NAME}_cache
    hostname: ${APP_NAME}_cache
    ports:
      - ${DOCKER_BRIDGE}:6379:6379

  node:
    image: node:12-slim
    restart: always
    container_name: ${APP_NAME}_node
    hostname: ${APP_NAME}_node
    working_dir: /app
    ports:
      - ${DOCKER_BRIDGE}:3333:3333
    volumes:
      - ./:/app:rw,cached
    command: ["/app/docker/node/start.sh"]
    tty: true
    depends_on:
      - db
      - db_testing
      - cache

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK}
